sonar.projectKey=Eduardo0500_microfrontends
sonar.organization=eduardo0500

# Fuentes de los tres microfrontends + utilidades compartidas
sonar.sources=framework_angular/src,framework_react/src,framework_vue/src,shared
sonar.sourceEncoding=UTF-8

# Excluir dependencias, builds y documentación
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.md,**/assets/**

# Tests (para cobertura cuando se ejecuten en CI)
sonar.tests=framework_angular/src,framework_react/src
sonar.test.inclusions=**/*.spec.ts
